#
# docker compose file to configure all tools for monitoring stack
#
version: "3"

services:

  # Prometheus is a time-series database that stores our metric data by pulling it periodically over HTTP
  prometheus:
    image: prom/prometheus:v2.31.1
    container_name: monitoring-prometheus
    # uses the promethus.yml configuration file in current directory
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
  
  # promtail is the agent component that provides the usual plugin mode to filter and transforms our log traces 
  promtail:
    image: grafana/promtail:2.4.1
    container_name: monitoring-promtail
    volumes:
      - $PWD/promtail.yml:/etc/promtail/promtail.yaml
      - /home/jadson/development/temp/log:/var/log/
    command: "--config.file=/etc/promtail/promtail.yaml"
    ports:
      - "9080:9080"

  # Loki is a logging management system created as part of the Grafana project,  
  # Allow store log to be shown in grafana
  loki:
    image: grafana/loki:2.4.1
    container_name: monitoring-loki
    volumes:
      - $PWD/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  # Grafana is the open source analytics & monitoring solution for every database.    
  grafana:
    image: grafana/grafana:8.2.5
    container_name: monitoring-grafana
    # configure grafana , see how this work (https://github.com/thbrunzendorf/monitoring-demo)
    #volumes:
    #  - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    #  - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    #  - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    #  - ./grafana/example.json:/var/lib/grafana/dashboards/example.json
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki


