#
# Loki Configuration File
#
# Receive the push from promtail in port 3100 (http://localhost:3100/loki/api/v1/push)
#
auth_enabled: false 
 
server: 
  http_listen_port: 3100 
  grpc_listen_port: 9096 
 
# ingester configuration 
# ingester is the responsable to receive de logs 
ingester: 
  wal: 
    enabled: true 
    dir: /tmp/wal 
  lifecycler: 
    address: 127.0.0.1 
    ring: 
      kvstore: 
        store: inmemory 
      replication_factor: 1 
    final_sleep: 0s 
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed 
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h 
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first 
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m) 
  max_transfer_retries: 0     # Chunk transfers disabled 

#####################################################3
# the part of store logs in loki 
#####################################################3
schema_config: 
  configs: 
    - from: 2020-10-24 
      store: boltdb-shipper 
      object_store: filesystem 
      schema: v11 
      index: 
        prefix: index_ 
        period: 24h 
 
storage_config: 
  boltdb_shipper: 
    # Ingesters keep writing the index to BoltDB files in
    # BoltDB Shipper keeps looking for new and updated files in that directory every 15 Minutes to upload them to the shared object store. 
    active_index_directory: /tmp/loki/boltdb-shipper-active 

    # An Index Gateway will download and synchronize the index, and it will serve it over gRPC to Queriers and Rulers.
    # Queriers lazily loads BoltDB files from shared object store to configured cache_location
    cache_location: /tmp/loki/boltdb-shipper-cache 
    
    # means if index files for a period are not used for 24 hours they would be removed from cache location.
    # Can be increased for faster performance over longer query periods, uses more disk space 
    cache_ttl: 24h         
    shared_store: filesystem 

  # Very simply it stores all the objects (chunks) in the specified directory:
  # At some point there is a limit to how many chunks can be stored in a single directory, Loki user ran into a strange error with about 5.5 million chunk files   
  filesystem: 
    directory: /tmp/loki/chunks 
 
compactor: 
  working_directory: /tmp/loki/boltdb-shipper-compactor 
  shared_store: filesystem 
 
limits_config: 
  reject_old_samples: true 
  reject_old_samples_max_age: 168h 
 
chunk_store_config: 
  max_look_back_period: 0s 
 
table_manager: 
  retention_deletes_enabled: false 
  retention_period: 0s 
 
ruler: 
  storage: 
    type: local 
    local: 
      directory: /tmp/loki/rules 
  rule_path: /tmp/loki/rules-temp 
  alertmanager_url: http://localhost:9093 
  ring: 
    kvstore: 
      store: inmemory 
  enable_api: true
