#
# Prometheus Configuration File
# 
# Define the applications address where the Promethues will collect the metrics
#

global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'monitoring_demo_job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.12:8080']