#
# Prometheus Configuration File
# 
# Define the applications address where the Promethues will collect the metrics
#

global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'monitoring_demo_job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.0.1:8083']
    # basic authentication on spring boot
    # this will generate a header:
    # Authorization Basic cHJvbWV0aGV1czpwcm9tZXRoZXVz
    basic_auth:
      username: "prometheus"
      password: "prometheus"

  - job_name: 'monitoring_base_job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.0.1:8083']
    basic_auth:
      username: "prometheus"
      password: "prometheus"    

  - job_name: 'monitoring_system_job'
    metrics_path: '/system/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.0.1:8082']
    basic_auth:
      username: "prometheus"
      password: "prometheus"  
  
