#
# Prometheus Configuration File
# 
# Define the applications address where the Promethues will collect the metrics
#

global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'monitoring_demo_job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.0.1:8080']
    basic_auth:
      username: "prometheus"
      password: "prometheus"

  - job_name: 'monitoring_talento_job'
    metrics_path: '/talento/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.0.1:8081']
    basic_auth:
      username: "prometheus"
      password: "prometheus"  

  #- job_name: 'monitoring_jerimum_job'
  #  metrics_path: '/jerimumjobs/actuator/prometheus'
  #  scrape_interval: 5s
  #  static_configs:
  #    - targets: ['172.18.0.1:8081']
  #  basic_auth:
  #    username: 'prometheus'
  #    password: 'prometheus'      
